### ISSUE TITLE
question about initialize the outgoing weights

### ISSUE THREAD

**Issue by Fragile-azalea** [google-research/growneuron#4]
Hi, authors. When I reproduce the quite valuable work with PyTorch, I notice that the authors say "we initialize the outgoing weights for all methods to small random values(eplision=1e-4)". However, all config files set grow_epsilon to 0. Am I misunderstanding the meaning of grow_epsilon? Do you mind pointing out my mistake?

**Comment by evcu** [comment]
You are correct. To be able to compare our method with Firefly we ran our experiments with non-zero epsilon. If you like to reproduce the results you can set grow_epsilon to 1e-4. However, for gradmax, epsilon has no (or very little) impact on final results as shown in Figure-5-center.

**Comment by AmanGoyal99** [comment]
> Hi, authors. When I reproduce the quite valuable work with PyTorch, I notice that the authors say "we initialize the outgoing weights for all methods to small random values(eplision=1e-4)". However, all config files set grow_epsilon to 0. Am I misunderstanding the meaning of grow_epsilon? Do you mind pointing out my mistake?

Can you share your pytorch implementation ?
