### ISSUE TITLE
Error when using current scipy version (1.8.1)

### ISSUE THREAD

**Issue by rfrels** [google-research/growneuron#5]
Hello authors, 
I encountered an error when growing with gradmax and using scipy version 1.8.1. 
I'm pretty sure that just some function got moved. 
With scipy 1.6.3 and 1.7.3 the error didn't occur, so I would recommend specifying sciypy version 1.7.3 in setupy.py.  
The configuration and error are below, for reproduction. 

Kind regards.
 
configuration:
python growneuron/cifar/main.py --output_dir=/tmp/cifar \
--config=growneuron/cifar/configs/grow_round_robin.py \
--config.grow_type=add_gradmax\
--config.updater.start_iteration=1000
error:
File "growneuron\growneuron\growers.py", line 405, in get_growth_directions
AttributeError: module 'scipy.sparse.linalg._eigen.arpack.arpack' has no attribute 'svds'

**Comment by evcu** [comment]
Thanks! Updated the requirements.

[7401194](https://github.com/google-research/growneuron/commit/7401194adb5d4a20ac3fd1a13e871ccb0e56024c)
