### ISSUE TITLE
Unable to activate virtual environment after running bash file

### ISSUE THREAD

**Issue by AmanGoyal99** [google-research/growneuron#6]
Greetings,

I was unable to see any virtual environment folder being created even after running 'run.sh'. Please let me know how can I activate the virtual environment as mentioned in readme file.

Thanks

**Comment by evcu** [comment]
There is no more virtual environment creating in the run.sh so the README.md needs update; will look into it this week. Let me know if you get it to work with `pip install .`

https://github.com/google-research/growneuron/commit/95da417d06a2e84272d143d4f03874ea04e4399d

**Comment by AmanGoyal99** [comment]
Do you know whether there is a pytorch version of your repo? If so, could you redirect me to that?

**Comment by evcu** [comment]
None that I know is public yet.

**Comment by evcu** [comment]
Updated README.md to reflect that no virtual environment is used.
