### ISSUE TITLE
Question about auxiliary tensors

### ISSUE THREAD

**Issue by julien-mille** [google-research/growneuron#7]
Hi Utku,
I was trying to relate what is done in **AddGradMax.get_growth_directions**, with the derivations of appendices A and B of your ICLR2022 paper.
As I understood, what you get in **grow_matrices** is the gradient of loss w.r.t to the auxiliary weight matrix $W^{aux}_l$, according to Eq (19) for conv layers, and Eq (14) for dense layers. Am I right?
If so, then it seems to me that you perform the SVD decomposition on this gradient (which corresponds to the product $\frac{\partial L}{\partial z_{l+1}} h^T_{l-1}$), coming from a single batch only, and not an average (expectation) over the dataset, as indicated by Eq (11).
If I had to compute $E_D[\frac{\partial L}{\partial z_{l+1}} h^T_{l-1}]$, faithfully to Eq (11), I would rather loop over the dataset, and sum up the gradients of auxiliary weight matrix $W^{aux}_l$ from all batches.
Am I missing something?

**Comment by julien-mille** [comment]
Oops. I read again the paper carefully, and found you actually mention this point at the end of Section 3. The gradient of Waux is actually computed on a large minibatch instead of the full dataset. I am closing the issue

**Comment by evcu** [comment]
Yes, we have a plot on the effect of this. It's easy on CIFAR-10 to do a very large batch. For ImageNet we can indeed calculate gradients using more than 1 batch. Note that with random data augmentations one can't really do full-gradient.
